/**
 * Error code prefixes by error category.
 */

/** Configuration error codes */
export enum ConfigErrorCode {
  MISSING_REQUIRED_CONFIG = "CONFIG_MISSING_REQUIRED",
  INVALID_CONFIG_VALUE = "CONFIG_INVALID_VALUE",
  CONFIG_FILE_NOT_FOUND = "CONFIG_FILE_NOT_FOUND",
  CONFIG_FILE_PARSE_ERROR = "CONFIG_FILE_PARSE_ERROR",
}

/** Authentication error codes */
export enum AuthErrorCode {
  MISSING_CONNECTION_STRING = "AUTH_MISSING_CONNECTION_STRING",
  MISSING_SAS_TOKEN = "AUTH_MISSING_SAS_TOKEN",
  AZURE_AD_FAILED = "AUTH_AZURE_AD_FAILED",
  INVALID_AUTH_METHOD = "AUTH_INVALID_AUTH_METHOD",
  ACCESS_DENIED = "AUTH_ACCESS_DENIED",
  CONNECTION_FAILED = "AUTH_CONNECTION_FAILED",
}

/** Network error codes */
export enum NetworkErrorCode {
  CONNECTION_FAILED = "NET_CONNECTION_FAILED",
  TIMEOUT = "NET_TIMEOUT",
  TRANSIENT_ERROR = "NET_TRANSIENT_ERROR",
}

/** General error codes */
export enum GeneralErrorCode {
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}

/** Repository replication error codes */
export enum RepoErrorCode {
  REPO_NOT_FOUND = "REPO_NOT_FOUND",
  REPO_AUTH_MISSING = "REPO_AUTH_MISSING",
  REPO_ARCHIVE_DOWNLOAD_FAILED = "REPO_ARCHIVE_DOWNLOAD_FAILED",
  REPO_EXTRACTION_FAILED = "REPO_EXTRACTION_FAILED",
  REPO_UPLOAD_FAILED = "REPO_UPLOAD_FAILED",
  REPO_RATE_LIMITED = "REPO_RATE_LIMITED",
  REPO_PATH_TRAVERSAL = "REPO_PATH_TRAVERSAL",
  REPO_MISSING_PARAMS = "REPO_MISSING_PARAMS",
  REPO_INVALID_SYNC_CONFIG = "REPO_INVALID_SYNC_CONFIG",
  REPO_SYNC_PAIR_FAILED = "REPO_SYNC_PAIR_FAILED",
}
